import { createId, saveState } from './data.js';
import { calculateBalance, cashMovement } from './transactions.js';
import { escapeHtml, formatCurrency, formatDate, localDateValue, statusBadge } from './utils.js';

const today = localDateValue();
const journalStatuses = ['Approved', 'Posted'];
function cashName(state, accountId) { return state.cashAccounts.find((account) => account.id === accountId)?.name || 'Cash'; }
function expenseAccount(state, category) { return state.categories.find((item) => item.name === category)?.account || 'Beban Lain-lain'; }
function line(journalId, transaction, account, debit, credit, description) { return { journalId, date: transaction.date, referenceNumber: transaction.id, sourceTransaction: transaction.id, account, debit, credit, description, createdBy: transaction.createdBy || 'Cantya Puspa' }; }
function pair(journalId, transaction, debitAccount, creditAccount, amount, description) { return [line(journalId, transaction, debitAccount, amount, 0, description), line(journalId, transaction, creditAccount, 0, amount, description)]; }
function transactionJournal(state, transaction) { if (!journalStatuses.includes(transaction.status)) return []; const journalId = `JRN-${transaction.id}`; const cashAccount = cashName(state, transaction.cashAccountId); if (transaction.type === 'petty-expense') return pair(journalId, transaction, expenseAccount(state, transaction.category), cashAccount, transaction.amount, transaction.description); if (transaction.type === 'petty-topup' || transaction.type === 'petty-replenishment') return pair(journalId, transaction, cashAccount, cashName(state, transaction.sourceCashAccountId), transaction.amount, transaction.description); if (transaction.type === 'cash-in') return pair(journalId, transaction, cashAccount, transaction.category || 'Pendapatan Lain-lain', transaction.amount, transaction.description); if (transaction.type === 'cash-out') return pair(journalId, transaction, expenseAccount(state, transaction.category), cashAccount, transaction.amount, transaction.description); if (transaction.type === 'cash-transfer') return pair(journalId, transaction, cashName(state, transaction.cashAccountId), cashName(state, transaction.sourceCashAccountId), transaction.amount, transaction.description); return []; }
export function syncJournals(state) { state.journals = state.transactions.flatMap((transaction) => transactionJournal(state, transaction)); return state.journals; }
function journalTotals(state) { return syncJournals(state).reduce((total, row) => ({ debit: total.debit + row.debit, credit: total.credit + row.credit }), { debit: 0, credit: 0 }); }
function renderJournal(state) { const totals = journalTotals(state); const journals = syncJournals(state).slice().reverse(); return `<div class="section-head"><div><span class="eyebrow">ACCOUNTING</span><h2>Jurnal Umum</h2><p>Jurnal otomatis hanya dibuat dari transaksi yang memenuhi status posting.</p></div><span class="status approved">${totals.debit === totals.credit ? 'Balanced' : 'Unbalanced'}</span></div><div class="metrics"><article class="metric-card"><span class="label">Total Debit</span><div class="value">${formatCurrency(totals.debit)}</div></article><article class="metric-card"><span class="label">Total Credit</span><div class="value">${formatCurrency(totals.credit)}</div></article><article class="metric-card"><span class="label">Selisih</span><div class="value">${formatCurrency(totals.debit - totals.credit)}</div></article></div><div class="panel"><div class="panel-header"><div><h3>Automatic General Journal</h3><p>Source transaction tidak digandakan saat halaman dibuka ulang.</p></div></div>${journals.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Journal ID</th><th>Date</th><th>Reference</th><th>Account</th><th>Debit</th><th>Credit</th><th>Description</th></tr></thead><tbody>${journals.map((row) => `<tr><td>${escapeHtml(row.journalId)}</td><td>${formatDate(row.date)}</td><td>${escapeHtml(row.referenceNumber)}</td><td>${escapeHtml(row.account)}</td><td>${formatCurrency(row.debit)}</td><td>${formatCurrency(row.credit)}</td><td>${escapeHtml(row.description)}</td></tr>`).join('')}</tbody></table></div>` : '<div class="empty-state">Belum ada jurnal posted.</div>'}</div>`; }
function cashBookRows(state) { const rows = []; state.cashAccounts.forEach((account) => rows.push({ date: '1900-01-01', id: `OPEN-${account.id}`, description: `Opening balance - ${account.name}`, cashIn: account.openingBalance, cashOut: 0, accountId: account.id })); state.transactions.filter((transaction) => journalStatuses.includes(transaction.status)).forEach((transaction) => state.cashAccounts.forEach((account) => { const movement = cashMovement(transaction, account.id); if (movement) rows.push({ date: transaction.date, id: transaction.id, description: transaction.description || transaction.id, cashIn: movement > 0 ? movement : 0, cashOut: movement < 0 ? Math.abs(movement) : 0, accountId: account.id }); })); return rows.sort((a, b) => a.date.localeCompare(b.date) || a.id.localeCompare(b.id)); }
function renderCashBook(state) { const balances = {}; const rows = cashBookRows(state).map((row) => { balances[row.accountId] = (balances[row.accountId] || 0) + row.cashIn - row.cashOut; return { ...row, balance: balances[row.accountId] }; }); return `<div class="section-head"><div><span class="eyebrow">ACCOUNTING</span><h2>Buku Kas</h2><p>Running balance dihitung terpisah untuk setiap akun kas.</p></div></div><div class="panel"><div class="panel-header"><div><h3>Cash Book</h3><p>${rows.length} baris pergerakan kas.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Cash Account</th><th>Reference</th><th>Description</th><th>Cash In</th><th>Cash Out</th><th>Balance</th></tr></thead><tbody>${rows.map((row) => `<tr><td>${row.date === '1900-01-01' ? '-' : formatDate(row.date)}</td><td>${escapeHtml(cashName(state, row.accountId))}</td><td>${escapeHtml(row.id)}</td><td>${escapeHtml(row.description)}</td><td>${formatCurrency(row.cashIn)}</td><td>${formatCurrency(row.cashOut)}</td><td>${formatCurrency(row.balance)}</td></tr>`).join('')}</tbody></table></div></div>`; }
function renderReconciliation(state) { const rows = (state.reconciliations || []).slice().reverse(); return `<div class="section-head"><div><span class="eyebrow">ACCOUNTING</span><h2>Rekonsiliasi Kas</h2><p>Bandingkan saldo sistem dengan saldo fisik atau bank statement.</p></div></div><div class="transaction-layout"><form class="panel transaction-form" data-reconciliation-form><div class="panel-header"><div><h3>Input Rekonsiliasi</h3><p>Difference = Actual Balance - System Balance.</p></div></div><div class="form-grid"><div class="field full"><label for="reconCashAccountId">Cash Account</label><select id="reconCashAccountId" name="cashAccountId" required><option value="">Pilih Cash Account</option>${state.cashAccounts.map((account) => `<option value="${account.id}">${escapeHtml(account.name)}</option>`).join('')}</select></div><div class="field"><label for="reconDate">Tanggal</label><input id="reconDate" name="reconDate" type="date" value="${today}" required></div><div class="field"><label for="actualBalance">Actual / Bank Balance</label><input id="actualBalance" name="actualBalance" type="number" min="0" step="1" required></div><div class="field full"><label for="reconcilingItem">Reconciling Item</label><input id="reconcilingItem" name="reconcilingItem" type="text" required></div><div class="field full"><label for="reconNotes">Notes</label><input id="reconNotes" name="notes" type="text" required></div><div class="form-actions"><button class="button-primary">Simpan Rekonsiliasi</button></div></div></form><div class="panel"><div class="panel-header"><div><h3>Reconciliation History</h3><p>Status dihitung dari selisih saldo aktual dan sistem.</p></div></div>${rows.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Account</th><th>System</th><th>Actual</th><th>Difference</th><th>Reconciling Item</th><th>Status</th></tr></thead><tbody>${rows.map((row) => `<tr><td>${formatDate(row.reconDate)}</td><td>${escapeHtml(row.cashAccountName)}</td><td>${formatCurrency(row.systemBalance)}</td><td>${formatCurrency(row.actualBalance)}</td><td>${formatCurrency(row.difference)}</td><td>${escapeHtml(row.reconcilingItem)}</td><td>${statusBadge(row.status)}</td></tr>`).join('')}</tbody></table></div>` : '<div class="empty-state">Belum ada rekonsiliasi.</div>'}</div></div>`; }
export function renderAccounting(view, state) { if (view === 'cash-book') return renderCashBook(state); return renderJournal(state); }
export function bindAccounting(view, state, render, showToast) { if (view !== 'reconciliation') return; const form = document.querySelector('[data-reconciliation-form]'); if (!form) return; form.onsubmit = (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(form).entries()); const account = state.cashAccounts.find((item) => item.id === values.cashAccountId); const actualBalance = Number(values.actualBalance); const systemBalance = calculateBalance(state, account.id); const difference = actualBalance - systemBalance; state.reconciliations ||= []; state.reconciliations.push({ id: createId('REC'), ...values, cashAccountName: account.name, actualBalance, systemBalance, difference, status: difference === 0 ? 'Balanced' : 'Has Difference' }); saveState(state); showToast('Rekonsiliasi berhasil disimpan'); render(view); }; }
