import { createId, saveState } from './data.js';
import { escapeHtml, formatCurrency, formatDate, localDateValue, statusBadge } from './utils.js';

const definitions = {
  'petty-topup': { title: 'Pembentukan / Top-Up Dana', eyebrow: 'PETTY CASH', type: 'petty-topup', idPrefix: 'PCT', submitLabel: 'Simpan Top-Up', fields: [['date', 'Tanggal', 'date'], ['sourceCashAccountId', 'Kas / Bank Sumber', 'cash'], ['cashAccountId', 'Petty Cash Tujuan', 'petty-cash'], ['amount', 'Nominal', 'number'], ['description', 'Keterangan', 'text']] },
  'petty-expenses': { title: 'Pengeluaran Petty Cash', eyebrow: 'PETTY CASH', type: 'petty-expense', idPrefix: 'PCV', submitLabel: 'Simpan Voucher', fields: [['date', 'Tanggal', 'date'], ['department', 'Departemen', 'department'], ['category', 'Kategori', 'category'], ['cashAccountId', 'Petty Cash', 'petty-cash'], ['vendor', 'Vendor / Supplier (manual)', 'text'], ['amount', 'Nominal', 'number'], ['description', 'Keterangan', 'text']] },
  'petty-replenishment': { title: 'Replenishment Petty Cash', eyebrow: 'PETTY CASH', type: 'petty-replenishment', idPrefix: 'PCR', submitLabel: 'Hitung & Simpan Replenishment', fields: [['date', 'Tanggal', 'date'], ['sourceCashAccountId', 'Kas / Bank Sumber', 'cash'], ['cashAccountId', 'Petty Cash', 'petty-cash'], ['description', 'Keterangan', 'text']] },
  'cash-in': { title: 'Kas Masuk', eyebrow: 'KAS OPERASIONAL', type: 'cash-in', idPrefix: 'CIN', submitLabel: 'Simpan Kas Masuk', fields: [['date', 'Tanggal', 'date'], ['cashAccountId', 'Kas Tujuan', 'cash-any'], ['category', 'Kategori / Sumber', 'text'], ['amount', 'Nominal', 'number'], ['description', 'Keterangan', 'text']] },
  'cash-out': { title: 'Kas Keluar', eyebrow: 'KAS OPERASIONAL', type: 'cash-out', idPrefix: 'COUT', submitLabel: 'Simpan Kas Keluar', fields: [['date', 'Tanggal', 'date'], ['cashAccountId', 'Kas Sumber', 'cash-any'], ['department', 'Departemen', 'department'], ['category', 'Kategori', 'category'], ['vendor', 'Vendor / Supplier (manual)', 'text'], ['amount', 'Nominal', 'number'], ['description', 'Keterangan', 'text']] },
  'cash-transfer': { title: 'Transfer Kas / Bank-to-Cash', eyebrow: 'KAS OPERASIONAL', type: 'cash-transfer', idPrefix: 'TRF', submitLabel: 'Simpan Transfer', fields: [['date', 'Tanggal', 'date'], ['sourceCashAccountId', 'Kas / Bank Sumber', 'cash-any'], ['cashAccountId', 'Kas / Bank Tujuan', 'cash-any'], ['amount', 'Nominal', 'number'], ['description', 'Keterangan', 'text']] },
  'cash-request': { title: 'Cash Request', eyebrow: 'TRANSAKSI', type: 'cash-request', idPrefix: 'CR', submitLabel: 'Submit Cash Request', fields: [['date', 'Tanggal Pengajuan', 'date'], ['requester', 'Requester', 'text'], ['department', 'Departemen', 'department'], ['category', 'Kategori', 'category'], ['amount', 'Estimasi Nominal', 'number'], ['requiredDate', 'Diperlukan Pada', 'date'], ['description', 'Tujuan / Keperluan', 'text']] },
};

export function cashMovement(transaction, accountId) {
  if (transaction.status !== 'Approved' && transaction.status !== 'Posted') return 0;
  if (transaction.type === 'cash-transfer') return transaction.cashAccountId === accountId ? transaction.amount : transaction.sourceCashAccountId === accountId ? -transaction.amount : 0;
  if (transaction.cashAccountId !== accountId) return 0;
  return ['cash-in', 'petty-topup', 'petty-replenishment'].includes(transaction.type) ? transaction.amount : ['cash-out', 'petty-expense'].includes(transaction.type) ? -transaction.amount : 0;
}
export function calculateBalance(state, accountId) { const account = state.cashAccounts.find((item) => item.id === accountId); return (account?.openingBalance || 0) + state.transactions.reduce((sum, transaction) => sum + cashMovement(transaction, accountId), 0); }
function options(type, state, currentValue = '') { const list = type === 'department' ? state.departments.map((item) => item.name) : type === 'category' ? state.categories.map((item) => item.name) : state.cashAccounts.filter((item) => type === 'petty-cash' ? item.type === 'Petty Cash' : true).map((item) => item.id); return list.map((value) => `<option value="${escapeHtml(value)}" ${value === currentValue ? 'selected' : ''}>${escapeHtml(type.includes('cash') ? state.cashAccounts.find((item) => item.id === value)?.name || value : value)}</option>`).join(''); }
function inputFor([key, label, type], state, transaction = {}) { if (['department', 'category', 'vendor', 'cash', 'petty-cash', 'cash-any'].includes(type)) return `<select name="${key}" id="${key}" required><option value="">Pilih ${label}</option>${options(type, state, transaction[key])}</select>`; const value = transaction[key] ?? (type === 'date' ? localDateValue() : ''); const extra = type === 'number' ? 'min="1" step="1"' : ''; return `<input id="${key}" name="${key}" type="${type}" value="${escapeHtml(value)}" ${extra} required>`; }
function tableFor(view, state) { const definition = definitions[view]; const rows = state.transactions.filter((transaction) => transaction.type === definition.type).slice().reverse(); if (!rows.length) return '<div class="empty-state">Belum ada transaksi pada modul ini.</div>'; return `<div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Tanggal</th><th>Detail</th><th>Nominal</th><th>Status</th></tr></thead><tbody>${rows.map((row) => `<tr><td><strong>${escapeHtml(row.id)}</strong></td><td>${formatDate(row.date)}</td><td>${escapeHtml(row.description || row.purpose || row.employee || row.requester || '-')}</td><td>${formatCurrency(row.amount)}</td><td>${statusBadge(row.status)}</td></tr>`).join('')}</tbody></table></div>`; }
export function renderTransaction(view, state) { const definition = definitions[view]; const petty = state.cashAccounts.find((account) => account.type === 'Petty Cash'); const balance = petty ? calculateBalance(state, petty.id) : 0; const isReplenishment = view === 'petty-replenishment'; return `<div class="section-head"><div><span class="eyebrow">${definition.eyebrow}</span><h2>${definition.title}</h2></div><span class="date-pill">${isReplenishment ? `Saldo saat ini: ${formatCurrency(balance)}` : 'Draft tersimpan di LocalStorage'}</span></div><div class="transaction-layout"><form class="panel transaction-form" data-transaction-form="${view}"><div class="panel-header"><div><h3>Input Transaksi</h3><p>Field bertanda wajib harus diisi sebelum disimpan.</p></div></div><div class="form-grid">${definition.fields.map((field) => `<div class="field ${field[0] === 'description' || field[0] === 'purpose' ? 'full' : ''}"><label for="${field[0]}">${field[1]}</label>${inputFor(field, state)}</div>`).join('')}${isReplenishment ? '<div class="field full"><div class="alert">Nominal replenishment dihitung dari dana imprest dikurangi saldo saat ini.</div></div>' : ''}<div class="form-actions"><button type="reset" class="button-secondary">Reset</button><button class="button-primary">${definition.submitLabel}</button></div></div></form><div class="panel"><div class="panel-header"><div><h3>Riwayat ${definition.title}</h3><p>Status awal transaksi mengikuti segregation of duties.</p></div></div>${tableFor(view, state)}</div></div>`; }
export function bindTransaction(view, state, render, showToast) { const form = document.querySelector(`[data-transaction-form="${view}"]`); if (!form) return; form.addEventListener('submit', (event) => { event.preventDefault(); const definition = definitions[view]; const values = Object.fromEntries(new FormData(form).entries()); const amount = view === 'petty-replenishment' ? Math.max(0, calculateBalance(state, values.cashAccountId) ? (state.settings.pettyFund - calculateBalance(state, values.cashAccountId)) : 0) : Number(values.amount); if (['cash-transfer'].includes(view) && values.sourceCashAccountId === values.cashAccountId) return showToast('Kas sumber dan tujuan tidak boleh sama.'); if (!amount || amount <= 0) return showToast('Nominal harus lebih besar dari 0.'); if (view === 'petty-replenishment' && amount <= 0) return showToast('Saldo petty cash sudah mencapai fund imprest.'); const pendingTypes = ['petty-expense', 'cash-out', 'cash-request']; const transaction = { id: createId(definition.idPrefix), type: definition.type, ...values, amount, status: pendingTypes.includes(definition.type) ? 'Pending' : 'Posted', createdBy: state.currentUser.name }; state.transactions.push(transaction); saveState(state); showToast(`${transaction.id} berhasil disimpan dengan status ${transaction.status}`); render(view); }); }
